---
- name: créer le fichier config dans le dossier .ssh
  file:
    path: /home/vagrant/.ssh/config
    state: touch
- name:
  blockinfile:
    path: /home/vagrant/.ssh/config
    state: present
    block: |
    Host proxy
    HostName proxypic.francecentral.cloudapp.azure.com
    User stage
    IdentityFile ~/.ssh/id_rsa
    Host master
    HostName 10.0.1.70
    User stage
    IdentityFile ~/.ssh/id_rsa
    ProxyJump proxy
    Host slave
    HostName 10.0.1.80
    User stage
    IdentityFile ~/.ssh/id_rsa
    ProxyJump proxy
    Host server_test
    HostName ???.francecentral.cloudapp.azure.com
    User stage
    IdentityFile ~/.ssh/id_rsa
    Host dbtest
    HostName 10.0.1.11
    User stage
    IdentityFile ~/.ssh/id_rsa
    ProxyJump server_test
    Host server_prod
    HostName ???.francecentral.cloudapp.azure.com
    User stage
    IdentityFile ~/.ssh/id_rsa
    Host dbprod
    HostName 10.0.1.21
    User stage
    IdentityFile ~/.ssh/id_rsa
    ProxyJump server_prod