---
- name: créer le fichier config dans le dossier .ssh
  file:
    path: /home/vagrant/.ssh/config
    state: touch
- name:
  blockinfile:
    path: /home/vagrant/.ssh/config
    state: present
    block: 'Host proxy

    HostName proxypic.francecentral.cloudapp.azure.com

    User stage

    Host master

    HostName 10.0.1.70

    User stage

    ProxyJump proxy

    Host slave

    HostName 10.0.1.80

    User stage

    ProxyJump proxy'