---
# tasks file for TERRAFORM
- name:
  yum:
    name: unzip
- name: Download and unarchive terraform_0.12.21
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
