---
- name: Import the APT repo key (Debian)
  apt_key:
    keyserver: "{{ apt_key_server }}"
    id: "{{ apt_key_id }}"

- name: Create the APT repository (Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main"
    filename: "{{ azure_package_name }}"
    state: present

- name: Install the application package (Debian)
  apt:
    name: "{{ azure_package_name }}"
    update_cache: yes
