---
- name: Create the YUM repository (RedHat)
  yum_repository:
    name: "{{ yum_repo_name }}"
    description: "{{ yum_repo_description }}"
    baseurl: "{{ yum_repo_baseurl }}"
    gpgkey: "{{ repo_key_url }}"
    gpgcheck: yes
    enabled: yes

- name: Install the application package (RedHat)
  package:
    name: "{{ azure_package_name }}"
    state: present
