---
# handlers file for MONGODB
- name: Relance le Daemon
  systemd:
    daemon_reload: yes
  listen: reload_daemon

- name: restart MONGODB
  service:
    name: mongod
    state: restarted
    enable: yes
  listen: restart_mongo

