---
# tasks file for PYTHON
- name: 
  yum:
    name: epel-release
    state: present
- name:
  yum:
    name: python-pip
    state: present
- name:
  pip:
    name: ansible
- name:
  pip:
    name: docker-py
