---
# tasks file for ANSIBLE
- name: 
  yum:
    name: epel-release
    state: present
- name:
  yum:
    name: python-pip
    state: present
- name:
  pip:
    name: pip
    state: latest
- name:
  pip:
    name: ansible

        
