---
# tasks file for GIT
- name: supprimer GIT present
  yum:
   name: git
   state: absent
- name: dl pkg
  yum:
   name: https://centos7.iuscommunity.org/ius-release.rpm
   state: present
- name: isntall git2
  yum:
   name: git2u-all
   state: present
