name= "rg_pil"
location= "francecentral"
vmSize = "Standard_B1s"
# owner = "lynda"
# address_space= [ "10.0.0.0/16" ]
# name_vnet= "vnet_pic"

adress_prefix = "10.0.1.0/24"
adress_prefix2 = "10.0.2.0/24"
nameNIC1 = "myNIC1"
nameNIC2 = "myNIC2"
nameNIC1 = "myNIC3"
nameNIC2 = "myNIC4"
# nameSubnet ="subnet_pic"
nameIP1 = "myIP1"
nameIP2 = "myIP2"
