---
- name: Création du fichier repo
  file: 
    path: /etc/yum.repos.d/nginx.repo
    state: touch
- name: Edition du fichier repo
  blockinfile:
    path: /etc/yum.repos.d/nginx.repo
    state: present
    block: '[nginx]

      name=nginx repo
      
      baseurl=http://nginx.org/packages/mainline/centos/7/$basearch/
      
      gpgcheck=0
      
      enabled=1'
- name: installation
  yum:
    name: nginx
    state: present
#- name: edit conf file
#  template:
#    src: conf.j2
#    dest:  /etc/nginx/conf.d/default.conf
- name: enable service
  service: 
    name: nginx
    state: restarted
    enabled: yes