---
# tasks file for docker
- name: install yum-utils
  yum:
    name: yum-utils
    state: present
- name: install device mapper
  yum:
    name: device-mapper-persistent-data
    state: present
- name: install lvm2
  yum:
    name: lvm2
    state: present
- name: create a repo for docker
  shell:
    cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: install docker
  yum:
    name: docker-ce,docker-ce-cli,containerd.io
    state: present
- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes
- name: execution docker sans sudo
  user:
    name: alex
    shell: /bin/bash
    groups: docker
    append: yes
#- name: change mode
#  shell:
#    cmd: chmod 777 /var/run/docker.sock  

