# ---
# # # tasks file for MONGODB
# # # - name: create file mongodb
# # #   file:
# # #     path: /etc/yum.repos.d/mongodb-org-{{ version }}.repo
# # #     state: touch

# # # - name: write file conf
# # #   blockinfile:
# # #      path: /etc/yum.repos.d/mongodb-org-{{ version }}.repo
# # #      block: '[mongodb-org-4.2]

# # #      name=MongoDB Repository

# # #      baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/

# # #      gpgcheck=1

# # #      enabled=1

# # #      gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc'

# # # - name: install mongodb 
# # #   yum:
# # #    name: mongodb-org
# # #    state: present
# # #   notify:
# # #   - reload daemon
# # #   - start  mongo

# # # - name: change permission directory /var/lib/mongo
# # #   file:
# # #     path: /var/lib/mongo
# # #     owner: "{{ user_login_mongodb }}"

# # # - name:  change permission directory /var/log/mongodb
# # #   file:
# # #      path: /var/log/mongodb
# # #      owner: "{{ user_login_mongodb }}"
# # #   notify:
# # #   - reload_daemon
# # #   - restart_mongo
  
# # - name: create user admin
# #   mongodb_user:
# #     #login_port: "27017"
# #     database: "admin"
# #     name: "admin"
# #     #name: "root"
# #     password: "w32jjYdMZr"
# #     state: present
# #     roles: "userAdminAnyDatabase"

# # - name: create user
# #   mongodb_user:
# #     login_user: "root"
# #     login_password: "w32jjYdMZr"
# #     login_database: "admin"
# #     database: "Customers"
# #     name: "user1"
# #     password: "user1"
# #     state: present
# #     roles: readWrite

# ============================================
# Mongo DB
# ============================================

# on cree un repo pour mongo
- name: create repo file
  file: 
    path: /etc/yum.repos.d/mongodb.repo
    state: touch
- name: write repo
  blockinfile:
    path: /etc/yum.repos.d/mongodb.repo
    state: present
    block: |
      [MangoDB]
      name=MongoDB Repository
      baseurl=http://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://www.mongodb.org/static/pgp/server-4.2.asc

# on installe mongodb
- name: installation
  yum:
    name: mongodb-org
    state: present

# on configure mongodb
- name: accept remote connection
  template:
    src: conf.j2
    dest: /etc/mongod.conf

# on installe gcc et python
- name: installation de gcc et python devel
  yum:
    name:
    - gcc
    - python-devel
    - python-setuptools
    state: present

# on installe pymongo    
- name: install de pymongo
  easy_install:
    name: pymongo
    state: present

# on demarre mongo
- name: enable service
  service: 
    name: mongod
    state: restarted
    enabled: yes

# on cree un user dans mongo
- name: create admin user
  mongodb_user:
    database: admin
    name: admin
    password: '12345'
    state: present
    roles: dbAdminAnyDatabase
    
# on cree une base customers
- name: create utilisateur
  mongodb_user:
    login_user: admin
    login_password: '12345'
    login_database: admin
    database: customers
    name: utilisateur
    password: '54321'
    state: present
    roles: readWrite

# seeder la db
- name: créer le fichier customers.json
  template:
    src: customers.j2
    dest: /home/jpr/customers.json

# on ajoute des noms a la base customers
- name: appliquer mongoimport
  shell: 
    cmd: mongoimport --db=customers --collection=customer --file=customers.json
