---   
- hosts: server
  become: yes
  roles:
    - JAVA12

- hosts: db
  become: yes
  roles:
    - pymongo
    - MONGODB 
    
- hosts: server_test
  become: yes
  roles: 
    - RESTFULWEB1
- hosts: server_prod
  become: yes
  roles: 
    - RESTFULWEB2

