---
- host: localhost
  become: yes
  roles:
    - SSHCONFIG
    - TERRAFORM
    - GIT
- host: proxy
  become: yes
  roles:
    - NGINX
- host: master
  become: yes
  roles: 
    - GIT
    - JAVA8
    - JENKINS

- host: slave
  become: yes
  roles:
    - GIT
    - JAVA8
    - MAVEN
    - DOCKER
