FROM centos:7
LABEL maintainer="Jeff Geerling"
ENV container=docker

ENV pip_packages "ansible"

# Install systemd -- See https://hub.docker.com/_/centos/
RUN yum -y update; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Install requirements.
RUN yum makecache fast \
 && yum -y install deltarpm epel-release initscripts \
 && yum -y update \
 && yum -y install \
      sudo \
      which \
      python-pip \
 && yum clean all
 && yum -y install git

# Install Ansible via Pip.
RUN pip install $pip_packages

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file.
RUN mkdir -p /etc/ansible
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

RUN echo "Host *" >> ~/.ssh/config
RUN echo "StrictHostKeyChecking no" >> ~/.ssh/config
RUN echo "UserKnownHostsFile=/dev/null" >> ~/.ssh/config
RUN echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
RUN echo "Host server_test" >> ~/.ssh/config
RUN echo "Hostname dnsenvtest.francecentral.cloudapp.azure.com" >> ~/.ssh/config
RUN echo "User stage" >> ~/.ssh/config
RUN echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
RUN echo "Host dbtest" >> ~/.ssh/config
RUN echo "Hostname 10.0.1.60" >> ~/.ssh/config
RUN echo "User stage" >> ~/.ssh/config
RUN echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
RUN echo "ProxyJump server-test" >> ~/.ssh/config
RUN echo "Host server_prod" >> ~/.ssh/config
RUN echo "Hostname dnsenvprod.francecentral.cloudapp.azure.com" >> ~/.ssh/config
RUN echo "User stage" >> ~/.ssh/config
RUN echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
RUN echo "Host dbprod" >> ~/.ssh/config
RUN echo "Hostname 10.0.2.60" >> ~/.ssh/config
RUN echo "User stage" >> ~/.ssh/config
RUN echo "ProxyJump server-prod" >> ~/.ssh/config
RUN echo "IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config


VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd"]
